dataset_upload.settings:
  type: config_object
  label: 'NIRD API Configuration'
  mapping:
    nird_username:
      type: string
      label: 'NIRD API Authentication username'
    nird_password:
      type: string
      label: 'NIRD API Authentication password'
    nird_api_base_uri:
      type: uri
      label: 'NIRD API Base URI'
    nird_api_token_endpoint:
      type: string
      label: 'NIRD API Token endponint'
    nird_api_dataset_endpoint:
      type: string
      label: 'NIRD API Dataset endponint'
    nird_api_subject_endpoint:
      type: string
      label: 'NIRD API Subject endponint'
    nird_api_license_endpoint:
      type: string
      label: 'NIRD API Licence endponint'
    nird_api_state_endpoint:
      type: string
      label: 'NIRD API State endponint'
    nird_api_category_endpoint:
      type: string
      label: 'NIRD API Category endpoint'
    nird_api_person_endpoint:
      type: string
      label: 'NIRD API Person endponint'
    nird_api_organization_endpoint:
      type: string
      label: 'NIRD API Organization endponint'
    data_manager_longname:
      type: string
      label: 'Default data manager org long name'
    data_manager_shortname:
      type: string
      label: 'Default data manager org short name'
    data_manager_contactemail:
      type: string
      label: 'Default data manager org contact email'
    data_manager_homepage:
      type: string
      label: 'Default data manager org homepage'
    upload_helptext:
      type: text_format
      label: 'Dataset upload instructions'
    upload_dataset:
      type: text_format
      label: 'Dataset creation instructions'
    language:
      type: string
      label: 'Language code'
